### ISSUE TITLE
Ubuntu/Debian support

### ISSUE THREAD

**Issue by rakhenmanoa** [Kyuunex/hid-sony-clone-fix-dkms#1]
Hello, I have this kind of errror when I try to compile :
make -C /lib/modules/5.11.0-37-generic/build V=1 M=/home/rakhenmanoa/GIT/hid-sony-clone-fix-dkms modules
make[1] : on entre dans le répertoire « /usr/src/linux-headers-5.11.0-37-generic »
test -e include/generated/autoconf.h -a -e include/config/auto.conf || (                \
echo >&2;                                                       \
echo >&2 "  ERROR: Kernel configuration is invalid.";           \
echo >&2 "         include/generated/autoconf.h or include/config/auto.conf are missing.";\
echo >&2 "         Run 'make oldconfig && make prepare' on kernel src to fix it.";      \
echo >&2 ;                                                      \
/bin/false)
make -f ./scripts/Makefile.build obj=/home/rakhenmanoa/GIT/hid-sony-clone-fix-dkms \
single-build= \
need-builtin=1 need-modorder=1
make[2]: ***  Aucune règle pour fabriquer la cible « /home/rakhenmanoa/GIT/hid-sony-clone-fix-dkms/hid-sony-clone-fix.o », nécessaire pour « /home/rakhenmanoa/GIT/hid-sony-clone-fix-dkms/hid-sony-clone-fix.mod ». Arrêt.
make[1]: *** [Makefile:1849 : /home/rakhenmanoa/GIT/hid-sony-clone-fix-dkms] Erreur 2
make[1] : on quitte le répertoire « /usr/src/linux-headers-5.11.0-37-generic »
make: *** [Makefile:5 : all] Erreur 2

**Comment by qnxt** [comment]
I have no idea how to help you there. 

This project is meant for Arch Linux (and it's derivatives) and be built with `makepkg -si` command. 
I guess I should have written this in the readme.

I can certainly try getting it to work on Ubuntu but I have no idea how far I can get.
I will leave this issue open until I test it

**Comment by qnxt** [comment]
I attempted to get this to work in Ubuntu but failed. I'll just add a help-wanted label on this for now

**Comment by rakhenmanoa** [comment]
I compiled the module manually and it worked but somehow i dont't know why
dkms don't

**Comment by VitorRamos** [comment]
A quick hack for ubuntu so you don't have to use makepkg:
```bash
export VER=$(uname -r | cut -c1-4);
wget https://raw.githubusercontent.com/torvalds/linux/v$VER/drivers/hid/hid-ids.h
wget https://raw.githubusercontent.com/torvalds/linux/v$VER/drivers/hid/hid-sony.c
sed -i 's/drivers\/hid\///g' hid-sony-clone-fix.patch
git apply hid-sony-clone-fix.patch
mv hid-sony.c hid-sony-clone.c
make
```
To hotplug the driver:
```bash
sudo rmmod hid_sony
sudo insmod hid-sony-clone.ko 
```
It worked with the dragon controller

**Comment by rakhenmanoa** [comment]
Thank you so much, btw I manually patched the sony-hid.c file and then
build it match the kernel I'm using. It worked that way also

Le mar. 19 avr. 2022, 22:31, Vitor Ramos ***@***.***> a
écrit :

**Comment by jbbandos** [comment]
I managed to get this to build on mx linux with a slight adaptation from @VitorRamos code:
```
export VER=$(uname -r | cut -c1-3);
wget https://raw.githubusercontent.com/torvalds/linux/v$VER/drivers/hid/hid-ids.h
wget https://raw.githubusercontent.com/torvalds/linux/v$VER/drivers/hid/hid-sony.c
sed -i 's/drivers\/hid\///g' hid-sony-clone-fix.patch
git apply hid-sony-clone-fix.patch
mv hid-sony.c hid-sony-clone-fix.c
make
```
And then found out this patch (or equivalent) is already in the liquorix kernel for MX linux...

**Comment by rakhenmanoa** [comment]
Thank you very much.
I tested the kernel 6.2 and the new ds4 driver from sony works also by
default on it.

Le ven. 24 févr. 2023 à 11:52, Bernardo Bandos ***@***.***> a
écrit :

**Comment by qnxt** [comment]
Thanks for the update. If `hid-playstation` driver from 6.2 works out of the box, then I'll probably archive this project as there would be no need for this patch going forward. 
I'll wait for 6.2 to roll out in Arch and other distros and test it, before archiving.

**Comment by lourenko** [comment]
The modified version provided by @jbbandos works in Debian. Thank you.

**Comment by jobs-git** [comment]
> A quick hack for ubuntu so you don't have to use makepkg:
> 
> ```shell
> export VER=$(uname -r | cut -c1-4);
> wget https://raw.githubusercontent.com/torvalds/linux/v$VER/drivers/hid/hid-ids.h
> wget https://raw.githubusercontent.com/torvalds/linux/v$VER/drivers/hid/hid-sony.c
> sed -i 's/drivers\/hid\///g' hid-sony-clone-fix.patch
> git apply hid-sony-clone-fix.patch
> mv hid-sony.c hid-sony-clone.c
> make
> ```
> 
> To hotplug the driver:
> 
> ```shell
> sudo rmmod hid_sony
> sudo insmod hid-sony-clone.ko 
> ```
> 
> It worked with the dragon controller

I confirm that this works, but you have to update the obj-m in make file to:
````
obj-m += hid-sony-clone.o
````
