### ISSUE TITLE
Doesn`t seem  to be working on the current kernel version

### ISSUE THREAD

**Issue by winiciuscota** [Kyuunex/hid-sony-clone-fix-dkms#2]
I`m getting this errors in the end of the installation, the controller still doesn`t work on usb

Tried updating the version to my current kernel version without success, is there anything else I can  try?

![image](https://user-images.githubusercontent.com/6284656/161394114-1b0b1c2c-6cb2-4c21-95b0-d23caea46792.png)

**Comment by qnxt** [comment]
Do you have kernel headers installed for kernel version 5.15? I am not able to replicate this issue

For good measure, I pushed updates and updated instructions.

Apologies for taking very long to respond, I've been very busy

**Comment by winiciuscota** [comment]
It don`t get the error now and the package seems to be installed correctly, but at the moment I plug the controller the light flashes yellow a few times and then turns blue, then the whole system gets stuck and is only fixed after a reboot.
I get this error if trying to boot with the controller plugged in
![image](https://user-images.githubusercontent.com/6284656/168525168-190c0ae6-bf1f-4cc5-90a2-e082033c8fe9.png)

**Comment by qnxt** [comment]
(I keep forgetting to reply to issues)

You can perhaps try connecting the contrioller through a USB hub and see if it makes a difference. Other than that, I don't think I can help you with that issue. My patch was designed to fix one specific issue, and there are so many clone controllers, I can't possibly buy, test, and patch their issues. My support to this whole endavour goes only as far as making sure the patch installs only.
