### ISSUE TITLE
Controller not showing up, but is recognized 

### ISSUE THREAD

**Issue by jurassicjordan** [Kyuunex/hid-sony-clone-fix-dkms#3]
So I got this to work on one computer, but not the other. Probably because of a kernel update but I’m not sure. On one PC it works flawless, on the other...not so much. When I plug the controller in, the kernal recognizes it as a ps4 controller, but doesn’t show up in JStest, OpenRGB, steam or qtjoy. While on the other PC it was working fine and was able to even work with gyro. I’m I missing a permission or something?

Distro: EndeavourOS (both)
Kernel: working PC: 5.18 (erased sadly)
             Nonworking: 5.19
Mobo: working: Omen Obilisk 875
            Nonworking: phantom gaming z590

**Comment by qnxt** [comment]
i have no clue. 
please provide more information. 
i need:
- kernel versions and distros used of both pcs
- dmesg log. from the part where you plug the controller in until it's end.
- maybe the motherboard model too. different USB controllers may do different things.

you can also try connecting it through a USB hub and see if it makes a difference

**Comment by jurassicjordan** [comment]
> i have no clue. please provide more information. i need:
> 
> * kernel versions and distros used of both pcs
> * dmesg log. from the part where you plug the controller in until it's end.
> * maybe the motherboard model too. different USB controllers may do different things.
> 
> you can also try connecting it through a USB hub and see if it makes a difference

I’ll include the info in an edit, just a moment

**Comment by qnxt** [comment]
I still don't have much to go on to help you, especially dmesg logs.

for now I updated this project to 5.18, 5.19, and 6.0. they are in their own branches. you can try them but there really are no changes in the driver itself. just some HID ids are updated.

**Comment by qnxt** [comment]
i also strongly encourage you to try through a USB hub, if you have a USB hub. for me at least, it disconnects and reconnects every few seconds if i don't use a USB hub. it could help.
